name: cml-fin
channels:
  - pip
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip:
    - ICPy
    - lingam
    - kneed
    - git+https://github.com/jakobrunge/tigramite.git
  - mkl <2022
  - pandas
  - openpyxl
  - numpy
  - scipy>=1.10.0
  - tqdm
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - statsmodels
  - lightgbm
  - seaborn
  - causalnex
  - fastparquet
